spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
logging:
  level:
    com.swjd: debug
mybatis-plus:
  type-aliases-package: com.swjd.demo3mp.pojo # 别名扫描包
  #mapper-locations: classpath*:/mappers/*.xml # mapper的xml文件地址
  global-config:
    db-config:
      id-type: auto # 全局主键策略，默认为自增长
      #update-strategy: not_null # 更新时，只更新非null字段
      #insert-strategy: not_null # 新增时，只新增非null字段


